#!/usr/bin/env bash
# Install/build the application without Docker.
# Intended for production hosts where PostgreSQL, Redis and a reverse proxy are
# provided by the system or by managed services.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVIRONMENT="${ENVIRONMENT:-production}"
BACKEND_DIR="$ROOT_DIR/search_api_solr"
FRONTEND_DIR="$ROOT_DIR/front"
BACKEND_VENV="${BACKEND_VENV:-$BACKEND_DIR/.venv}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
PNPM_STORE_DIR="${PNPM_STORE_DIR:-$ROOT_DIR/.pnpm-store}"
UV_CACHE_DIR="${UV_CACHE_DIR:-/tmp/uv-cache}"
RUN_MIGRATIONS="${RUN_MIGRATIONS:-false}"

if [[ "$ENVIRONMENT" == "production" && "${DISABLE_AUTH:-false}" != "true" ]]; then
  if [[ -z "${SECRET_KEY:-}" && -z "${JWT_SECRET:-}" ]]; then
    echo "ERROR: SECRET_KEY or JWT_SECRET must be set for production when auth is enabled." >&2
    exit 1
  fi
fi

if [[ ! -f "$ROOT_DIR/.env.$ENVIRONMENT" ]]; then
  echo "ERROR: .env.$ENVIRONMENT not found" >&2
  exit 1
fi

DATABASE_URL="${DATABASE_URL:-postgresql://search_user:search_password@127.0.0.1:5432/search_db}"
REDIS_URL="${REDIS_URL:-redis://127.0.0.1:6379/0}"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-/api}"
INTERNAL_API_URL="${INTERNAL_API_URL:-http://127.0.0.1:8007}"

echo "Preparing backend environment: $BACKEND_DIR/.env.local"
cat > "$BACKEND_DIR/.env.local" << EOL
# Generated by install_no_docker.sh - DO NOT EDIT DIRECTLY
$(grep -v '^#' "$ROOT_DIR/.env.shared" | grep -v '^$' || true)
$(grep -v '^#' "$ROOT_DIR/.env.$ENVIRONMENT" | grep -v '^$' || true)
DATABASE_URL=$DATABASE_URL
REDIS_URL=$REDIS_URL
API_PORT=8007
DEV=${DEV:-false}
SECRET_KEY=${SECRET_KEY:-${JWT_SECRET:-}}
JWT_SECRET=${JWT_SECRET:-${SECRET_KEY:-}}
SESSION_SECRET=${SESSION_SECRET:-${SECRET_KEY:-${JWT_SECRET:-}}}
EOL

echo "Preparing frontend environment: $FRONTEND_DIR/.env.local"
cat > "$FRONTEND_DIR/.env.local" << EOL
# Generated by install_no_docker.sh - DO NOT EDIT DIRECTLY
$(grep -v '^#' "$ROOT_DIR/.env.shared" | grep -v '^$' || true)
$(grep -v '^#' "$ROOT_DIR/.env.$ENVIRONMENT" | grep -v '^$' || true)
NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
INTERNAL_API_URL=$INTERNAL_API_URL
EOL

echo "Installing backend dependencies..."
if command -v uv >/dev/null 2>&1; then
  UV_CACHE_DIR="$UV_CACHE_DIR" uv venv --allow-existing --python "$PYTHON_BIN" "$BACKEND_VENV"
  UV_CACHE_DIR="$UV_CACHE_DIR" uv pip install --python "$BACKEND_VENV/bin/python" -r "$BACKEND_DIR/requirements.txt"
else
  "$PYTHON_BIN" -m venv "$BACKEND_VENV"
  "$BACKEND_VENV/bin/python" -m pip install --upgrade pip
  "$BACKEND_VENV/bin/python" -m pip install -r "$BACKEND_DIR/requirements.txt"
fi

if [[ "$RUN_MIGRATIONS" == "true" ]]; then
  echo "Running backend migrations..."
  (
    cd "$BACKEND_DIR"
    "$BACKEND_VENV/bin/alembic" upgrade head
  )
fi

echo "Installing frontend dependencies and building..."
(
  cd "$FRONTEND_DIR"
  corepack enable
  pnpm install --frozen-lockfile --store-dir "$PNPM_STORE_DIR"
  if [[ -e .next ]]; then
    mv .next ".next.previous.$(date +%s)" 2>/dev/null || rm -rf .next
  fi
  NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" INTERNAL_API_URL="$INTERNAL_API_URL" pnpm build
)

cat << EOL

No-Docker install complete.

Backend:
  cd $BACKEND_DIR
  $BACKEND_VENV/bin/uvicorn app.main:app --host 127.0.0.1 --port 8007 --workers 4

Frontend:
  cd $FRONTEND_DIR
  HOSTNAME=127.0.0.1 PORT=3000 node .next/standalone/server.js

Reverse proxy:
  route /api/ to http://127.0.0.1:8007/
  route / to http://127.0.0.1:3000/
EOL
