#!/bin/bash
# Script pour synchroniser les environnements entre les services
# Usage: ./scripts/sync_env.sh [development|production|staging]

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 [development|production|staging]"
    exit 1
fi

ENVIRONMENT=$1

# Vérifier que le fichier d'environnement existe
if [ ! -f ".env.$ENVIRONMENT" ]; then
    echo "Error: .env.$ENVIRONMENT not found"
    exit 1
fi

echo "Synchronizing environment: $ENVIRONMENT"

# Créer les fichiers .env pour chaque service

# Pour le frontend
echo "Creating front/.env.local..."
mkdir -p front
cat > front/.env.local << EOL
# Generated by sync_env.sh - DO NOT EDIT DIRECTLY
# Environment: $ENVIRONMENT
# Base configuration
$(cat .env.shared | grep -v "^#" | grep -v "^$")

# Environment-specific configuration
$(cat .env.$ENVIRONMENT | grep -v "^#" | grep -v "^$")

# Overrides from Docker setup (if available)
NEXT_PUBLIC_API_URL=http://localhost:${API_PORT:-8003}
REACT_APP_API_URL=http://localhost:${API_PORT:-8003}
API_BASE_URL=http://localhost:${API_PORT:-8003}
FRONTEND_URL=http://localhost:${FRONTEND_PORT:-3003}
EOL

# Pour le backend
echo "Creating search_api_solr/.env.local..."
mkdir -p search_api_solr
cat > search_api_solr/.env.local << EOL
# Generated by sync_env.sh - DO NOT EDIT DIRECTLY
# Environment: $ENVIRONMENT
# Base configuration
$(cat .env.shared | grep -v "^#" | grep -v "^$")

# Environment-specific configuration
$(cat .env.$ENVIRONMENT | grep -v "^#" | grep -v "^$")

# Overrides from Docker setup (if available)
REDIS_URL=redis://redis:6379/0
POSTGRES_PORT=${POSTGRES_PORT:-5435}
API_PORT=8007
EOL

# Copier .env.local en .env pour le container Docker (qui ne charge pas .env.local automatiquement)
echo "Creating front/.env..."
cp front/.env.local front/.env

echo "Environment synchronization complete!"
echo "Frontend: front/.env.local + front/.env"
echo "Backend: search_api_solr/.env.local"